<a href="https://colab.research.google.com/github/Mbigdeli2003/Game-Theory/blob/main/Nash_finder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install nashpy

In [6]:
import nashpy as nash
import numpy as np

# Define the payoff matrices for both players
A = np.array([[1, 3, 2],
              [0, 2, 5],
              [6, 1, 4]])

B = np.array([[1, 0, 6],
              [3, 2, 1],
              [6, 1, 4]])

# Create the game
game = nash.Game(A, B)

# Calculate Nash equilibria
equilibria = game.support_enumeration()

# Print the Nash equilibria
print("Nash equilibria:")
for eq in equilibria:
    print(eq)
game

Nash equilibria:
(array([0., 0., 1.]), array([1., 0., 0.]))


Bi matrix game with payoff matrices:

Row player:
[[1 3 2]
 [0 2 5]
 [6 1 4]]

Column player:
[[1 0 6]
 [3 2 1]
 [6 1 4]]